### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by LennyBEL** [xanxTV/MDC-Panel#1]
Under "[Death Report](https://mdc.xanx.co.uk/paperwork-generators/death-report)"
-> "Administrative Information" -> "Handling Detective / **Foresnsic** Analyst"

![image](https://user-images.githubusercontent.com/19469646/87661959-cccd8e80-c761-11ea-836f-b82dc3409034.png)

**Comment by CXDezign** [comment]
Thanks for the report :)

**Comment by CXDezign** [comment]
Now fixed in the following commit: https://github.com/xanxTV/MDC-Panel/commit/b55f99a70de54daa4d8ee3dd8aaa783f108bbbc7
